import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { findCanvaLinuxProjectRoot as findProjectRoot } from "../../canva-linux/project-root.js";

const repoRoot =
  findProjectRoot(
    process.env.CANVA_SCRIPT_REPO_ROOT ||
      (process.argv[1] ? path.dirname(path.resolve(process.argv[1])) : process.cwd()),
  );
const useBuildOutput = process.argv.includes("--build-output");
const runtimeRoot = useBuildOutput ? path.join(repoRoot, ".build") : repoRoot;

function resolveEntryPoint(name: string): string {
  const tsEntry = path.join(repoRoot, "build-resources", "electron", "preload", `${name}.ts`);
  if (fs.existsSync(tsEntry)) {
    return tsEntry;
  }

  throw new Error(
    `[preload-bundle] missing TypeScript entrypoint: ${path.relative(repoRoot, tsEntry)}`,
  );
}

async function buildPreloadBundle(name: string, outputName: string): Promise<void> {
  const entryPoint = resolveEntryPoint(name);
  const outputFile = path.join(
    runtimeRoot,
    ...(useBuildOutput ? ["electron"] : ["build-resources", "electron"]),
    "preload",
    outputName,
  );

  if (!fs.existsSync(entryPoint)) {
    throw new Error(
      `[preload-bundle] missing entrypoint: ${path.relative(repoRoot, entryPoint)}`,
    );
  }

  await esbuild.build({
    entryPoints: [entryPoint],
    outfile: outputFile,
    bundle: true,
    platform: "node",
    target: "es2022",
    format: "esm",
    plugins: [
      {
        name: "electron-shim",
        setup(build) {
          build.onResolve({ filter: /^electron$/ }, (args) => {
            return { path: args.path, namespace: "electron-shim" };
          });
          build.onLoad({ filter: /^electron$/, namespace: "electron-shim" }, () => {
            return {
              contents:
                'export default require("electron"); export const contextBridge = require("electron").contextBridge; export const ipcRenderer = require("electron").ipcRenderer;',
              loader: "js",
            };
          });
        },
      },
    ],
    sourcemap: false,
    minify: false,
    legalComments: "none",
    logLevel: "info",
    banner: {
      js: [
        "// Generated by build-resources/c420ui/scripts/build-preload-bundle.ts using esbuild.",
        "// Do not edit this file directly. Edit build-resources/electron/preload source modules instead.",
      ].join("\n"),
    },
  });

  console.log(`[preload-bundle] wrote ${path.relative(repoRoot, outputFile)}`);
}

export async function main(): Promise<void> {
  await buildPreloadBundle("canva", "canva.bundle.mjs");
  await buildPreloadBundle("toolbar", "toolbar.bundle.mjs");
}

if (/build-preload-bundle\.(mjs|js|ts)$/.test(process.argv[1] || "")) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
