import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { failResult, okResult, type ValidationContext, type ValidationResult } from "./result";
import { info, ok, warn } from "../../c420ui/host/ui";

export function runAppImageValidation(context: ValidationContext, args: string[]): ValidationResult {
  const { rootDir } = context;
  const extractCheck = args.includes("--extract-check");
  const skipReleaseManifest = args.includes("--skip-release-manifest");

  const distDir = path.join(rootDir, "dist");
  if (!fs.existsSync(distDir)) {
    return failResult(["dist directory not found"]);
  }

  const appimages = fs.readdirSync(distDir)
    .filter((file) => file.endsWith(".AppImage"))
    .sort();

  if (appimages.length === 0) {
    return failResult(["No AppImage artifact found under dist/"]);
  }

  if (appimages.length > 1) {
    warn("Multiple AppImage artifacts found; validating all and using the first as canonical output");
  }

  const failures: string[] = [];

  for (const file of appimages) {
    const artifact = path.join(distDir, file);
    const stats = fs.statSync(artifact);

    if (stats.size === 0) {
      failures.push(`AppImage artifact is empty: ${artifact}`);
      continue;
    }

    // Check executable permission
    if ((stats.mode & 0o111) === 0) {
      if (!context.dryRun) {
        fs.chmodSync(artifact, stats.mode | 0o111);
        warn(`Added executable permission: ${artifact}`);
      }
    }

    ok(`Valid AppImage artifact: ${artifact}`);
    info(`Size: ${stats.size} bytes`);

    const checksumFile = `${artifact}.sha256`;
    if (fs.existsSync(checksumFile)) {
      info(`Validating AppImage checksum: ${checksumFile}`);
      const shaResult = spawnSync(
        "sha256sum",
        ["-c", path.basename(checksumFile)],
        { cwd: distDir, encoding: "utf8" },
      );
      if (shaResult.status === 0) {
        ok("AppImage checksum validation passed");
      } else {
        failures.push(`AppImage checksum validation failed for ${file}`);
      }
    }
  }

  if (failures.length > 0) return failResult(failures);

  const primaryAppImage = path.join(distDir, appimages[0] ?? "");
  info(`Primary AppImage artifact: ${primaryAppImage}`);

  if (skipReleaseManifest) {
    info("Skipping complete release SHA256SUMS validation");
  } else {
    const manifestPath = path.join(distDir, "SHA256SUMS");
    if (fs.existsSync(manifestPath)) {
      info("Validating SHA256SUMS");
      const shaResult = spawnSync(
        "sha256sum",
        ["-c", "SHA256SUMS"],
        { cwd: distDir, encoding: "utf8" },
      );
      if (shaResult.status === 0) {
        ok("SHA256SUMS validation passed");
      } else {
        failures.push("SHA256SUMS validation failed");
      }
    } else {
      info("dist/SHA256SUMS not found; complete release manifest is generated by the release workflow");
    }
  }

  if (extractCheck) {
    info("Optional AppImage extraction check enabled.");
    const tmpdir = spawnSync("mktemp", ["-d"], { encoding: "utf8" }).stdout.trim();
    try {
      const extractResult = spawnSync(
        primaryAppImage,
        ["--appimage-extract"],
        { cwd: tmpdir, stdio: "ignore" },
      );
      if (extractResult.status === 0) {
        ok("AppImage extraction check passed.");
      } else {
        warn("AppImage extraction check failed. The artifact may still run normally with FUSE.");
      }
    } finally {
      fs.rmSync(tmpdir, { recursive: true, force: true });
    }
  }

  info("FUSE runtime check:");
  const hasFuse = spawnSync("command", ["-v", "fusermount3"], { shell: true }).status === 0 ||
                  spawnSync("command", ["-v", "fusermount"], { shell: true }).status === 0;

  if (hasFuse) {
    ok("FUSE mount helper found");
  } else {
    warn("FUSE mount helper not found. AppImage execution may fail.");
  }

  return failures.length > 0 ? failResult(failures) : okResult();
}

if (require.main === module) {
  const result = runAppImageValidation({ rootDir: process.cwd() }, process.argv.slice(2));
  process.exit(result.ok ? 0 : 1);
}
