import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import {
  c420uiBootstrapArtifactPath,
  C420UI_BOOTSTRAP_MANIFEST_PATH,
} from "../checks/bootstrap-check-helpers.js";

const manifestPath = C420UI_BOOTSTRAP_MANIFEST_PATH;
const uiEntrypoint = c420uiBootstrapArtifactPath("run-c420ui.mjs");
const cliEntrypoint = c420uiBootstrapArtifactPath("run-c420ui-cli.mjs");
const builderEntrypoint = c420uiBootstrapArtifactPath("c420ui-builder.mjs");

function readJson<T>(filePath: string): T {
  return JSON.parse(fs.readFileSync(filePath, "utf8")) as T;
}

test("c420ui bootstrap manifest exists and is generated by Rust", () => {
  const manifest = readJson<{
    kind: string;
    generatedBy: string;
    c420uiVersion: string;
    dependentProject: string;
    dependentProjectVersion: string;
    entrypoint: string;
    cliEntrypoint: string;
    requiresNode: string;
    buildRecipe: string;
    buildTool: string;
    buildTarget: string;
    bundleFormat: string;
    moduleFormat: string;
    typescriptFirst: boolean;
    c420uiSourceHashAlgorithm: string;
    c420uiSourceHash: string;
    c420uiSourceHashInputs: string[];
    artifactHashes: Record<string, string>;
  }>(manifestPath);
  const rootPackageJson = readJson<{ version: string }>("package.json");
  const c420uiPackageJson = readJson<{ version: string }>("build-resources/c420ui/package.json");

  assert.equal(manifest.kind, "c420ui-bootstrap");
  assert.equal(manifest.generatedBy, "c420ui-host bootstrap");
  assert.equal(manifest.c420uiVersion, c420uiPackageJson.version);
  assert.equal(manifest.dependentProject, "canva-linux");
  assert.equal(manifest.dependentProjectVersion, rootPackageJson.version);
  assert.equal(manifest.entrypoint, "run-c420ui.mjs");
  assert.equal(manifest.cliEntrypoint, "run-c420ui-cli.mjs");
  assert.equal(manifest.requiresNode, ">=22.0.0");
  assert.equal(manifest.buildRecipe, "c420ui-host bootstrap");
  assert.equal(manifest.buildTool, "c420ui-host");
  assert.equal(manifest.buildTarget, "node22");
  assert.equal(manifest.bundleFormat, "thin-launcher");
  assert.equal(manifest.moduleFormat, "esm");
  assert.equal(manifest.typescriptFirst, false);
  assert.equal(manifest.c420uiSourceHashAlgorithm, "sha256");
  assert.match(manifest.c420uiSourceHash, /^sha256:[0-9a-f]{64}$/);
  assert.deepEqual(manifest.c420uiSourceHashInputs, ["build-resources/c420ui"]);
  for (const artifact of ["run-c420ui.mjs", "run-c420ui-cli.mjs", "c420ui-builder.mjs"] as const) {
    assert.match(manifest.artifactHashes[artifact], /^sha256:[0-9a-f]{64}$/);
  }
});

test("c420ui bootstrap entrypoints exist and are thin launchers", () => {
  for (const entrypoint of [uiEntrypoint, cliEntrypoint, builderEntrypoint]) {
    const stats = fs.statSync(entrypoint);
    const source = fs.readFileSync(entrypoint, "utf8");
    assert.equal(stats.isFile(), true, `${entrypoint} must be a file`);
    assert.ok(stats.size > 0, `${entrypoint} must not be empty`);
    assert.ok(stats.size < 5000, `${entrypoint} must stay a thin launcher`);
    assert.match(source, /spawnSync/);
    assert.doesNotMatch(source, /createInteractiveActionRunner/);
    assert.doesNotMatch(source, /createCanvaLinuxC420UIAdapter/);
    assert.doesNotMatch(source, /status-panels/);
    assert.doesNotMatch(source, /esbuild/);
  }
});

test("c420ui bootstrap entrypoints are syntactically valid JavaScript", () => {
  for (const entrypoint of [uiEntrypoint, cliEntrypoint, builderEntrypoint]) {
    const result = spawnSync(process.execPath, ["--check", entrypoint], {
      encoding: "utf8",
      shell: false,
    });

    assert.equal(
      result.status,
      0,
      `${entrypoint} must pass node --check: ${result.stderr || result.stdout}`,
    );
  }
});

test("run-c420ui.mjs routes directly to the Rust TUI binary", () => {
  const bundle = fs.readFileSync(uiEntrypoint, "utf8");

  assert.match(bundle, /c420ui-tui/);
  assert.match(bundle, /\["run", "--json-lines"/);
  assert.doesNotMatch(bundle, /runC420UIRustTuiApp/);
  assert.doesNotMatch(bundle, /createApp/);
  assert.doesNotMatch(bundle, /blessed-widgets/);
  assert.doesNotMatch(bundle, /function inputDialog\(/);
});

test("run-c420ui-cli.mjs delegates argv to c420ui-host", () => {
  const bundle = fs.readFileSync(cliEntrypoint, "utf8");
  assert.match(bundle, /c420ui-host/);
  assert.match(bundle, /process\.argv\.slice\(2\)/);
  assert.doesNotMatch(bundle, /action-run", "--json-lines"/);
});

test("build-bootstrap.ts delegates to rust-bootstrap", () => {
  const source = fs.readFileSync(
    path.join("build-resources", "c420ui", "scripts", "build-bootstrap.ts"),
    "utf8",
  );
  assert.match(source, /runC420UIRustBootstrap/);
  assert.doesNotMatch(source, /createC420UIBootstrapBuildOptions/);
  assert.doesNotMatch(source, /calculateC420UISourceHash/);
  assert.doesNotMatch(source, /artifactHashes\s*=/);
});
