import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";

const repoRoot =
  process.env.CANVA_SCRIPT_REPO_ROOT || path.resolve(__dirname, "..");
const useBuildOutput = process.argv.includes("--build-output");
const runtimeRoot = useBuildOutput ? path.join(repoRoot, ".build") : repoRoot;

function resolveEntryPoint(): string {
  if (useBuildOutput) {
    return path.join(runtimeRoot, "electron", "preload", "canva.js");
  }

  const tsEntry = path.join(runtimeRoot, "electron", "preload", "canva.ts");
  if (fs.existsSync(tsEntry)) {
    return tsEntry;
  }

  return path.join(runtimeRoot, "electron", "preload", "canva.js");
}

export async function main(): Promise<void> {
  const entryPoint = resolveEntryPoint();
  const outputFile = path.join(
    runtimeRoot,
    "electron",
    "preload",
    "canva.bundle.js",
  );

  if (!fs.existsSync(entryPoint)) {
    throw new Error(
      `[preload-bundle] missing entrypoint: ${path.relative(repoRoot, entryPoint)}`,
    );
  }

  await esbuild.build({
    entryPoints: [entryPoint],
    outfile: outputFile,
    bundle: true,
    platform: "node",
    target: "es2022",
    format: "cjs",
    external: ["electron"],
    sourcemap: false,
    minify: false,
    legalComments: "none",
    logLevel: "info",
    banner: {
      js: [
        "// Generated by scripts/build-preload-bundle.ts using esbuild.",
        "// Do not edit this file directly. Edit electron/preload source modules instead.",
        "'use strict';",
      ].join("\n"),
    },
  });

  console.log(`[preload-bundle] wrote ${path.relative(repoRoot, outputFile)}`);
}

if (require.main === module) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
